name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run backend tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_backend
    - name: Run single hop tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_single_hop
    - name: Run network tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_network
    - name: Run channel tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_channel
    - name: Run multi hop tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_multi_hop
    - name: Run classical storage tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_classical_storage
    - name: Run quantum storage tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_quantum_storage
    - name: Run host tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_host
    - name: Run host get any message
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_get_classical_any_host
